services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./cfg/srv/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:latest
    volumes:
      - ./php:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./mysql:/var/lib/mysql