services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./cfg/srv/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:latest
    volumes:
      - ./php:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    depends_on:
      - mysql